-- Drop the two tenant-less mini-apps: dating + moments/occasions.
--
-- Authorised by Salman 2026-09-30 after the investigation in
-- .claudedocs/work/tenantless-modules-audit/2026-09-30/summary.md and the contract in
-- .claudedocs/implementation/TENANTLESS_MODULES_REMOVAL_CONTRACT.md.
--
-- All four tables measured EMPTY twice, the second time immediately before this ran, with a
-- sealed read-only transaction and a positive control (clients=10, reservations=67) proving the
-- reader was not blind. No data is lost because there is no data.
--
-- Statement order generated by `prisma migrate diff` between two schema files (no datasource
-- connection): foreign keys first, then tables. No CASCADE — an unmeasured dependency must
-- surface as an error, not be swallowed.
BEGIN;

ALTER TABLE "public"."occasion_pages" DROP CONSTRAINT "occasion_pages_creator_id_fkey";
ALTER TABLE "public"."occasion_rsvps" DROP CONSTRAINT "occasion_rsvps_page_id_fkey";

DROP TABLE "public"."date_pages";
DROP TABLE "public"."occasion_creators";
DROP TABLE "public"."occasion_pages";
DROP TABLE "public"."occasion_rsvps";

COMMIT;
