"""The one place a catalog SKU is normalised, generated, or archived.

Ratified by Salman 2026-09-30 — A-Q2/Q3/Q4/Q5/Q6 in
`.claudedocs/plans/restaurant-vertical-product.md`. Migration:
`prisma/migrations/add_catalog_item_sku.sql`, executed 2026-09-30.

WHY THIS IS A MODULE AND NOT THREE HELPERS NEXT TO THREE CALL SITES
-------------------------------------------------------------------
Exactly the reason `app/core/phone.py` exists. A UI rule that says "SKUs are uppercase" is a good
experience and not a guarantee: a seed script, an API client, or a backfill will eventually send
something else. The normaliser at the write boundary is the guarantee, and there must be only one
of it, or the two copies drift and the unique index starts rejecting things nobody can explain.

THE RULES, AS DECIDED
---------------------
A-Q3  Generated by us from the item NAME, during upload/backfill -- never typed by the owner.
A-Q4  Normalised at the write boundary: UPPERCASE, A-Z 0-9 and dashes only. The index is
      case-sensitive, so 'shawarma-01' and 'SHAWARMA-01' would be two different keys; normalising
      on write is what makes that impossible rather than merely discouraged.
A-Q5  Never re-used. A SKU belongs to its item for life.
A-Q6  ...with ONE exception, and it is what makes A-Q5 workable: when an item is RETIRED, its SKU
      is archived (suffixed), which frees the clean SKU for the new menu.

🔴 WHY ARCHIVING THE SKU IS SAFE — the question A-Q5 and A-Q6 appear to contradict each other on
-------------------------------------------------------------------------------------------------
It looks like freeing the namespace would corrupt historical reports. It does not, and the reason
is structural rather than a judgement call: **`StoreOrderItem` references `catalogItemId`, a UUID.
It does not store a SKU at all** (verified against prisma/schema.prisma, 2026-09-30 -- its columns
are id, orderId, catalogItemId, quantity, unitPrice, totalPrice, color, size, createdAt).

So an order line keeps pointing at the same row whatever its SKU says, and every historical figure
stays exactly as it was. The SKU is a JOIN KEY FOR MENU UPDATES, not a historical record. If a
future change ever denormalises a SKU onto an order line, this reasoning breaks and A-Q6 must be
revisited -- which is why it is written down here rather than assumed.

NAMES ARE NOT UNIQUE, SO THE COUNTER IS LOAD-BEARING
----------------------------------------------------
`caracas` holds five duplicate item names in production. `generate()` therefore takes the SKUs
already in use for that tenant and increments -- SHAWARMA-01, SHAWARMA-02 -- rather than assuming
a name maps to one item.

TYPOS ARE PERMANENT, DELIBERATELY (Salman, 2026-09-30)
------------------------------------------------------
A SKU is an INTERNAL id for the database, the sync engine and Lia. The customer never sees it; the
customer sees `nameAr`/`nameEn`, which the owner may edit freely at any time without touching the
SKU. A misspelled name therefore yields a misspelled SKU forever, and that is the industry-standard
trade rather than a defect. An owner who wants a clean SKU retires the item and creates a new one.
"""

from __future__ import annotations

import re
import unicodedata
from datetime import datetime, timezone
from typing import Iterable, Optional

# A-Q4. The only characters a stored SKU may contain.
_ALLOWED = re.compile(r"[^A-Z0-9-]")
_DASHES = re.compile(r"-{2,}")

# The suffix that retires a SKU and frees its base (A-Q6). UPPERCASE-with-dashes rather than the
# `_archived_` form sketched in the decision, so an archived SKU still satisfies A-Q4's own rule --
# a value this module produced must survive being passed back through `normalise()` unchanged, or
# the two rules contradict each other the first time anything re-normalises a row.
ARCHIVE_MARKER = "-ARCHIVED-"

# Cap, so a pathological name cannot produce an unbounded key. Long enough that the archive suffix
# always fits beside a real SKU.
MAX_BASE = 48


def normalise(raw: Optional[str]) -> Optional[str]:
    """The stored form of a SKU, or None. Never raises.

    Accepts whatever a human, a script or an API client sent and returns the one representation the
    unique index will ever see. Never raising is deliberate and matches `phone.normalize_for_storage`:
    a write path must not fail because somebody typed a space.
    """
    if raw is None:
        return None
    # Strip accents so "Café" and "Cafe" cannot become two different keys.
    text = unicodedata.normalize("NFKD", str(raw))
    text = "".join(ch for ch in text if not unicodedata.combining(ch))
    text = _ALLOWED.sub("-", text.upper())
    text = _DASHES.sub("-", text).strip("-")
    return text or None


def slugify_name(name_en: Optional[str], name_ar: Optional[str] = None) -> str:
    """The BASE of a SKU, from an item's name.

    English first, because a SKU is an internal ASCII key and `normalise()` would strip an Arabic
    name to nothing. Falls back to Arabic transliteration-by-omission only to detect that case --
    it does not transliterate, it returns "ITEM", and the caller's counter then makes
    ITEM-01/ITEM-02 unique. That is honest: we do not pretend to romanise Arabic here, and an
    opaque-but-unique key is better than a wrong-but-readable one.
    """
    base = normalise(name_en)
    if base:
        return base[:MAX_BASE]
    # An Arabic-only name normalises to nothing; say so explicitly rather than returning "".
    return "ITEM"


def generate(name_en: Optional[str], name_ar: Optional[str], taken: Iterable[str]) -> str:
    """A SKU that is unique within `taken`, derived from the item's name. A-Q3.

    `taken` is every SKU already used by THIS TENANT — the uniqueness scope is
    `@@unique([clientId, sku])`, never global, so two restaurants may both hold SHAWARMA-01.

    The counter starts at 01 and is always present, even when the base is unused: a menu is a list
    of variants far more often than not, so SHAWARMA-01 today and SHAWARMA-02 tomorrow reads
    correctly, while SHAWARMA followed later by SHAWARMA-02 does not.
    """
    used = {normalise(s) for s in taken if s}
    base = slugify_name(name_en, name_ar)
    n = 1
    while True:
        candidate = f"{base}-{n:02d}"
        if candidate not in used:
            return candidate
        n += 1


def archive(sku: Optional[str], when: Optional[datetime] = None) -> Optional[str]:
    """Retire a SKU so its base becomes free again. A-Q6.

    Returns None for None, so a row that never had a SKU stays without one rather than acquiring a
    meaningless archived key.

    Idempotent in the sense that matters: archiving an ALREADY-archived SKU does not stack a second
    marker — it re-stamps the timestamp. Without that, deactivate/reactivate/deactivate would grow
    the key without bound and eventually collide with MAX length rather than with another row.
    """
    base = normalise(sku)
    if base is None:
        return None
    if ARCHIVE_MARKER in base:
        base = base.split(ARCHIVE_MARKER)[0]
    stamp = int((when or datetime.now(timezone.utc)).timestamp())
    return f"{base}{ARCHIVE_MARKER}{stamp}"


def is_archived(sku: Optional[str]) -> bool:
    """Whether this SKU has been retired. Used by tests and by any future re-use check."""
    return bool(sku) and ARCHIVE_MARKER in (normalise(sku) or "")
